Sprint 11
Kolesnikov-Eugene/FunImages pull request #4
Opened 2023-06-22 21:11 UTC by Kolesnikov-Eugene

2023-06-23 16:33 UTC, protos17 requested changes

2023-06-23 16:33 UTC, protos17 commented on FunImages/Auth/SnakeCaseJSONDecoder.swift
> +class SnakeCaseJSONDecoder: JSONDecoder {
Придумано отлично! Но рекомендую его еще сделать final, потому что он не наследуется

2023-06-23 16:33 UTC, protos17 commented on FunImages/Auth/URLRequest+Extensions.swift
> +            let token = OAuth2TokenStorage.shared.token!
Не рекомендую использовать принудительное извлечение опционалов, лучше добавить проверку через guard let

2023-06-23 16:33 UTC, protos17 commented on FunImages/OAuth2/OAuth2Service.swift
> +                self.task = nil
task рекомендую обнулять не только при успешном результате, а при любом

2023-06-23 16:33 UTC, protos17 commented on FunImages/OAuth2/OAuth2TokenStorage.swift
> +            }
Рекомендую еще добавить метод удаления ключа, когда идет присваивание nil

2023-06-23 16:33 UTC, protos17 commented on FunImages/Profile/ProfileImageService.swift
> +                        completion(.success(self.avatarURL!))
Рекомендую аккуратнее работать с опционалами здесь и в других местах. Принудительное извлечение опционалов может часто приводит к вылетам приложения

2023-06-23 16:33 UTC, protos17 commented on FunImages/Profile/ProfileResult.swift
> +    let bio: String
Чтобы правильно работала программа, необходимо сделать lastName и bio опциональными

2023-06-23 16:33 UTC, protos17 commented on FunImages/Profile/ProfileService.swift
> +    var profileData: Profile?
Если свойство снаружи используется только для чтения, рекомендую указывать как private(set)

2023-06-23 16:33 UTC, protos17 commented on FunImages/SplashView/File.swift
Рекомендую удалить, лежит в файлах проекта

2023-06-23 16:33 UTC, protos17 commented on FunImages/SplashView/SplashViewController.swift
> +        oauth2Storage.token ?? nil
oauth2Storage.token уже имеет тип данных String?, нет необходимости указывать значение при отсутствии значения nil (то есть то же самое отсутствие значения))

2023-06-23 16:33 UTC, protos17 commented on FunImages/SplashView/SplashViewController.swift
> +        if token != nil {
Здесь как раз пригодилось безопасное извлечение опционала:

if let token = token {
fetchProfile(token)
}

2023-06-23 16:33 UTC, protos17 commented on FunImages/SplashView/SplashViewController.swift
> +                fetchProfile(token!)
Очень много в проекте принудительного извлечения опционалов

2023-06-23 16:33 UTC, protos17 commented on FunImages/SplashView/SplashViewController.swift
> +                            print("success")
Printы обычно не приветствуются внутри основного кода приложения

2023-06-23 16:33 UTC, protos17 commented on FunImages/SplashView/SplashViewController.swift
> +        let action = UIAlertAction(title: "OK", style: .default) { [self] _ in
Рекомендую указать weak self

2023-06-26 21:12 UTC, Kolesnikov-Eugene commented on FunImages/SplashView/SplashViewController.swift
> +                fetchProfile(token!)
Пока работал над проектом, использовал принудительное извлечение, где был уверен, что значение будет. Понял, что далеко не лучшая практика) Лучше сразу использовать безопасное извлечение) Впредь буду аккуратнее)

2023-06-27 09:02 UTC, protos17 approved these changes

2023-06-27 09:02 UTC, protos17 commented on FunImages/OAuth2/OAuth2TokenStorage.swift
>      private init() { }
Рекомендую указать сразу после shared

2023-06-27 09:02 UTC, protos17 commented on FunImages/Profile/ProfileViewController.swift
> +    private var profileImageView: UIImageView = {
UI элементы рекомендую указывать как let или lazy var

2023-06-27 09:02 UTC, protos17 commented on FunImages/Profile/ProfileViewController.swift
> +        view.addSubview(profileImageView)
Можно указать так:

        [profileImageView,
         profileNameLabel ...].forEach { view.addSubview($0)}

2023-06-27 09:02 UTC, protos17 commented on FunImages/SplashView/SplashViewController.swift
> +                    username: self.profileService.profileData!.userName) { result in
ЗДесь тоже необходимо добавить weak self

2023-06-27 18:45 UTC, merged